image: macOS

cache:
  - $HOME/R

install:
  - brew install --cask r > /dev/null

build: off

test_script:
  - Rscript 'compile.R'
  - Rscript 'latex-pass.R'
  - appveyor AddMessage "$(cat message.txt)" -Details "$(cat details.txt)"
